spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 

  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

otp.message.queue: OTP_MESSAGE_QUEUE
jwt.token.secret: MySecretSecretJWTKey198xY34692022secureTokenKey3ForBackend
